### ISSUE TITLE
code a long instructions

### ISSUE THREAD

**Issue by olitreadwell** [learn-co-curriculum/python-p4-web-servers-and-wsgi#3]
### Canvas Link

https://my.learn.co/courses/654/assignments/33306?module_item_id=83817

### Concern

Maybe we can change the formatting for instructions in all lessons so that they're easier to tell apart from other content? 

Perhaps a blockquote?

> This lesson is a code along. Please fork and clone this lesson before continuing!

Also in this lesson do we need to tell the students to run 

```py
$ pipenv install
$ pipenv shell
```

before updating the instructions to indicate that we want the user to run 

`$ python -m http.server`

It seems like we want to make it explicit/obvious what code / commands we want the students to run. 

### Suggested Changes

make instructions explicit and format them as blockquotes to make it highlight them as being different from the content of the lesson.

**Comment by linda-seiter** [comment]
Thanks for the suggestion, we'll be updating the code-alongs to emphasize that step in the next curriculum version.
