### ISSUE TITLE
Command instructions didn't work 

### ISSUE THREAD

**Issue by mlinkenmeyer** [learn-co-curriculum/python-p4-web-servers-and-wsgi#4]
### Canvas Link

https://learning.flatironschool.com/courses/6813/assignments/257119?module_item_id=608000

### Concern

This command didn't work for me. Additionally, a different server opened up for the very first command on this page. 

Run python server/werkzeug_app.py (or change the file to be executable first if you prefer). You should see the following in the terminal:

 python server/werkzeug_app.py
 => WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 => * Running on http://localhost:5555/ (Press CTRL+C to quit)

**Comment by linda-seiter** [comment]
I just tested both and they work.  Make sure you ran "pipenv install && pipenv shell" first, and that you copied the code from the README into werkzeug_app.py and saved the file.
